apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gorush.fullname" . }}
  labels:
    app: {{ template "gorush.name" . }}
    chart: {{ template "gorush.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  stat.engine: memory
  production: "false"
