apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gorush.fullname" . }}
  labels:
    app: {{ template "gorush.name" . }}
    chart: {{ template "gorush.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.android.enable }}
 android_apikey: {{ .Values.android.apikey | quote }}
{{- end }}
{{- if .Values.ios.enable }}
 ios_base64: {{ .Values.ios.base64 | quote }}
{{- end }}
