apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gorush.fullname" . }}
  labels:
    app: {{ template "gorush.name" . }}
    chart: {{ template "gorush.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
 android_apikey: {{ .Values.android_apikey | quote }}
